title: Simple Salesforce
author: Tom Rook
logo: /assets/images/logo.png
description: Join Tom on his adevntures across the Salesforce ecosystem
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"